### ISSUE TITLE
Is this style for mac only?

### ISSUE THREAD

**Issue by furyscript** [connors/photon#127]
I see your official site page and I see your styles looks like mac os.

I would know if windows/linux users have same style or it change based on OS.

Thanks.

**Comment by holywyvern** [comment]
It looks exacly the same across al desktop and mobile versions.
It's just css styles than looks like Mac OS.

**Comment by pedzed** [comment]
Yes, this is a Mac-style only. But you can write your own CSS styles on top of it to write Linux/Windows specific styles.

Please, close this issue if your question is answered.
