### ISSUE TITLE
Menu Bar Component

### ISSUE THREAD

**Issue by L3V147H4N** [connors/photon#13]
I think a very common component in Desktop applications is Menu Bars and frankly, the one that Electron provides is kinda ugly.

I've been using angular-material lately and something like this would be nice, but much more compact. What I like most of photon is that is very compact in comparison to other css libraries/frameworks

Angular Material menu bar
[MenuBar](https://material.angularjs.org/latest/demo/menuBar 
)

**Comment by lucasmotta** [comment]
Usually the menu bar on OSX at least uses the system's default. Not sure if adding another type of menu bar would bring more confusion?

**Comment by L3V147H4N** [comment]
But Photon is meant to be Cross Platform, and other operating systems do not have OSX-Like Menus

**Comment by connors** [comment]
@L3V147H4N The intent with Photon is to use as much of the native components as possible. By using the default menu behaviors for each platform, you get tons of stuff for free. Things like keyboard shortcuts are included by default without having to re-implement them in css and js. 

I agree that we need to improve the menus... I'd rather keep them native.
