### ISSUE TITLE
It's wrong

### ISSUE THREAD

**Issue by Suremotoo** [connors/photon#146]
position: js/menu.js
```js
// Add the listener
document.addEventListener('DOMContentLoaded', function () {
  document.querySelector('.js-context-menu').addEventListener('click', function (event) {
    menu.popup(remote.getCurrentWindow());
  })
})
```

TypeError: Cannot read property 'addEventListener' of null

**Comment by mrdotkg** [comment]
Could you please explain what is the issue and steps to reproduce?

**Comment by Suremotoo** [comment]
My steps:
1、git clone repo
2、cd repo && npm intsall
3、start 

The project is working, but browser console show error 
```js
TypeError: Cannot read property 'addEventListener' of null
```
i fixed, .js-context-menu  it not found, remove it ,it's ok!
