### ISSUE TITLE
Docs: thoughts on adding titles to icons?

### ISSUE THREAD

**Issue by malantonio** [connors/photon#17]
Just wondering if there'd be interest in adding `title` attributes to the icon examples in the docs? I'm finding the current layout makes locating the right class name a bit tricky. 

Something like:

```html
<span class="icon icon-check" title="icon-check"></span>
```

for

![screen shot 2015-10-14 at 10 08 29 am](https://cloud.githubusercontent.com/assets/2744987/10486146/9754cd0a-725b-11e5-8488-d4130e184dac.png)

I'd be happy to submit a PR!

**Comment by cwhite92** [comment]
I have overwhelming support for this idea :+1:
