### ISSUE TITLE
Table headers active

### ISSUE THREAD

**Issue by iamphill** [connors/photon#18]
When you click on the `thead` cell, instead of just highlighting the clicked cell, it highlights the whole row

**Comment by mszynka** [comment]
Are you using 'thead' for column or row header? If for row header it's intentional and intuitive to have highlighted whole row with content.

**Comment by iamphill** [comment]
So the [demo app](http://photonkit.com/demo-app.html) looks to represent a file browser like finder on mac and when clicking on the cell in the header it makes the whole row active (fine for the body). But for the header it should only highlight the cell.

Doing it this way would resemble how finder (and I'm sure explorer) does it - by only highlight the selected header cell, not the row.

Does that make more sense?

**Comment by visualfanatic** [comment]
Noticed the same thing, full support.

**Comment by mszynka** [comment]
@iamphill yes it does. It should highlight whole column. That's a legit issue. +1

**Comment by iamphill** [comment]
Looks like this was fixed by f6552970cd9d68548deb427e43df8d0d816fe8f1
