### ISSUE TITLE
Just want to say thanks

### ISSUE THREAD

**Issue by IonicaBizau** [connors/photon#23]
@connors Actually, I was wanting to build something like this but it's amazing to see it already done by you!  :smile: :tada:  :clap:

**Comment by bhaveshgohel** [comment]
:+1:

**Comment by horaceho** [comment]
:+1:

**Comment by kevyu** [comment]
:+1:

**Comment by connors** [comment]
:heart: :heart: :heart:

**Comment by IonicaBizau** [comment]
@connors Is this used in GitHub for Desktop, btw? Looks like OS X. :smile:
