### ISSUE TITLE
It seems that close buttons on the right for tabs is a more common practice? 

### ISSUE THREAD

**Issue by edwinyzh** [connors/photon#26]
First, really great UI components! I have always wanted a CSS UI framework designed for desktop apps.

I think you should add an option for placing the close buttons on the right side of the tabs, and by default it should be like that.

Just my 2 cents.

**Comment by developit** [comment]
@edwinyzh The default theme is geared towards OS X, which always places close buttons on the left side of any UI control. Since it sounds like you're looking to use this on a different platform, you're likely to get more info from Issue #6.

**Comment by connors** [comment]
Thanks@edwinyzh. Like @developit mentioned, this is the default behavior of the OS X platform. If you run an Electron app on Windows, the close button will be on the right. Photon doesn't place those controls.
