### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by paranoid-android** [connors/photon#35]
Hello,

PhotonKit looks great. However, it is unclear how to actually start an app. I followed the "Getting "Started" information. I downloaded the "Precompiled Photon" I can see the css, fonts, and template-app directories. However, I can't figure out what to do now. How do I run the thing?

**Comment by developit** [comment]
`npm install` to install everything, then run `npm start` to run Electron using `template-app`.

**Comment by paranoid-android** [comment]
@developit Thank you so much for your help. This cleared it right up for me.
