### ISSUE TITLE
Project name confusion

### ISSUE THREAD

**Issue by zsup** [connors/photon#36]
Hey @connors,

This project looks awesome and super useful - we've built an application with Electron and I can see how helpful this framework will be. That said, I'm wondering if I could convince you to change the name.

Backstory - I run a company called Particle; we make open source hardware development kits for IoT (used to be called Spark). Our latest development kit is called the Photon, and it's pretty popular; if you google 'Photon' we're the first result after the Wikipedia page on Photons. Our IDE, [Particle Dev](https://www.particle.io/dev), is on Github's list of projects built with Electron: http://electron.atom.io/

I worry that the name you've selected for this project will create confusion; although the projects do different things, they're both development tools. I'm wondering if I can convince you to change the name while the project is still young?

Thanks for considering!

**Comment by zsup** [comment]
Ah, well, since I originally wrote this, you guys have climbed the Google ranks; good on you :-) Regardless, I hope you'll be understanding of my request.

**Comment by developit** [comment]
Suggestion: `positron`

**Comment by connors** [comment]
Yeah names are hard. Obviously, you see why we went with Photon and how it relates to Electron. Considering your company name is Particle and not Photon, I'm personally not to worried about the confusion. I'd be willing to reconsider if it becomes a bigger issue.
