### ISSUE TITLE
Shouldn't be able to highlight two items in list-group

### ISSUE THREAD

**Issue by louy** [connors/photon#39]
Hi,

If you look at native UI components in OSX, you can't highlight two list items at the same time. The experience feels really weird when I have a selected item and I click on another one and both get highlighted.

I see two solutions here:

1. Don't highlight on `.list-group-item:active` (Finder.app behaves like this in sidebar)
2. Remove highlight on `.list-group:active .list-group-item.selected:not(:active)` (Finder.app behaves like this with folder content)

**Comment by connors** [comment]
Good catch. I actually see a few things wrong with my code here. I'll take a look this weekend.

**Comment by louy** [comment]
:+1: I solved it like this for now.

![screen shot 2015-10-17 at 01 43 12](https://cloud.githubusercontent.com/assets/349850/10554898/795053ee-7470-11e5-85f5-d51d53c04699.png)

**Comment by connors** [comment]
Fixed in https://github.com/connors/photon/commit/d017253d415919b4cc8adea3c786c1036f90c0c7.

**Comment by louy** [comment]
:+1: 
I did something similar in my new app [Lawha](https://github.com/louy/Lawha).
I had to rely on javascript because `:hover` doesn't work with `mousedown`.

Thanks for this awesome project btw 😊

**Comment by connors** [comment]
👍
