### ISSUE TITLE
Disabled State

### ISSUE THREAD

**Issue by paranoid-android** [connors/photon#51]
Hello,

In Photon, buttons have an `active` class available to them. It would be valuable if a `disabled` class was also available. An example of a disabled button can be seen in the Finder in OS X.

1. Open the Finder.
2. Click "Documents"
3. In the toolbar, you'll probably notice that the "Edit Tags" and "Share the selected items" buttons are disabled until you select one or more files.

**Comment by sbruchmann** [comment]
FWIW, an attribute selector would fit here as well/better.

**Comment by developit** [comment]
@sbruchmann Agreed!

**Comment by Delapouite** [comment]
Thanks for the PR @iamdade

**Comment by connors** [comment]
Fixed in 78236888ba306ee81c10b8d873e2d8ab816adce9
