### ISSUE TITLE
Input, Button etc. cursor-type

### ISSUE THREAD

**Issue by janbiasi** [connors/photon#55]
If i hover a button, input, textarea or something else, the cursor remains default. If not already added: Please add the <code>cursor: pointer</code> to those relevant elements! :smile_cat: **Thanks!!**

**Comment by connors** [comment]
@janbiasi That behavior is intentional as that's how native applications work.

**Comment by EmadAdly** [comment]
you can override by add 
```css
* {
  cursor: pointer !important;
}
```
or add it on custom attribute instead of *
