### ISSUE TITLE
Have a windows (metro) style too ? 

### ISSUE THREAD

**Issue by championswimmer** [connors/photon#70]
Using photon makes creating GUI a breeze, BUT, it looks really out of place when running such an app on Windows/Linux. 

Any plans to support Windows themed UI elements ?

**Comment by Martinspire** [comment]
+1, OSX-only seems like an odd choice for a desktop-theme

**Comment by iamdade** [comment]
You can check milestone, it's planned for v1.0.0

**Comment by bitwombat** [comment]
@championswimmer Are you talking about how Electron's menu is above the Photon header?  That struck me as odd too.  I guess you can do away with Electron's menu altogether (just not create one) and use toolbar-actions.

**Comment by kumarharsh** [comment]
@bitwombat I think what he meant was that the Mac look doesn't look *at home* in Windows or Linux.

**Comment by connors** [comment]
Dupe of #7
