### ISSUE TITLE
[Feature requests] Adding a loading component

### ISSUE THREAD

**Issue by midudev** [connors/photon#83]
First of all. Amazing work. Thanks for your effort. :)

I think that would be a good idea to add a loading component. Loading is basic stuff for a lot of apps and it would be nice to get a clean, OSX style, loading icon for photon.

Something like that, but neat and embed on the css.
http://www.cssscript.com/demo/ios-os-x-style-pure-css-loading-spinner/

**Comment by MauriceConrad** [comment]
Nice work, great.
